CREATE TABLE amigos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  apodo VARCHAR(150) DEFAULT NULL,
  telefono VARCHAR(20) NOT NULL,
  email VARCHAR(150) DEFAULT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;